### ISSUE TITLE
Error: Unauthenticated when upload GPX with POI

### ISSUE THREAD

**Issue by zmeel** [Flomp/wanderer#266]
When I create a route in GPX studio with POI's I cannot import these routes in Wanderer (running in Docker on a Synology NAS). I get the following error: {"message":"Error: Unauthenticated"}. Routes without POI's created in GPX studio just import fine.

![Image](https://github.com/user-attachments/assets/93d7a218-1c7c-4a4a-afcf-08a6721e9703)

**Comment by zmeel** [comment]
When I add waypoints to a trail in Wanderer and export the trail and then import the trail with waypoint I also get the same error: Unauthenticated. I tried to import this trail in https://demo.wanderer.to and then I get the same error.

**Comment by Flomp** [comment]
Thanks for the report. I replicated the issue and fixed it on the main branch. It will be included in the next patch.

**Comment by Flomp** [comment]
Fixed in v0.16.5.

**Comment by zmeel** [comment]
I updated the container and to my surprise I now get an file reading error even for GPX files without POI's.

![Image](https://github.com/user-attachments/assets/4f54079d-dbe1-4270-8b35-9397a8c2b319)

I have reinstalled everything from scratch (also deleting the data folder) but still the same error. Uploading a GPX file (with POI) to the demo site works.

**Comment by zmeel** [comment]
After trying several time the error disappeared and now the GPX file is imported. Maybe a browser cache issue?
